version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=jsoneditor
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
